### ISSUE TITLE
pod 'SQLite.swift/standalone' doesn't build any more

### ISSUE THREAD

**Issue by Trannosaur** [stephencelis/SQLite.swift#1015]
> Issues are used to track bugs and feature requests.
> Need  help or have a general question? Ask on Stack Overflow (tag sqlite.swift).

## Build Information

- I tried with both 0.12.0 and 0.12.2
- Xcode 11.6
- How do do you integrate SQLite.swift in your project?
    - CocoaPods

## General guidelines

- If I have this line:     pod 'SQLite.swift', '~> 0.12.2' then I can build the project, however, if I use     pod 'SQLite.swift/standalone', '~> 0.12.2' then the project won't build due to errors like: "Ambiguous use of 'SQLITE_DETERMINISTIC'"

Sadly this means I can't use FTS or anything since the non-standalone version isn't compatible.

- Provide as much information needed to _reliably reproduce_ the issue.
Create a new xcode project, 

Use this podfile: 
use_frameworks!

workspace 'targetname'

target 'targetname' do
    pod 'SQLite.swift/standalone', '~> 0.12.2'
    pod 'sqlite3/fts5', '= 3.15.0'  # SQLite 3.15.0 with FTS5 enabled

    platform :ios, '13.0'
end

**Comment by Trannosaur** [comment]
Just for funsies I hacked in the fix and changed Connection.swift:590 to flags |= **sqlite3**.SQLITE_DETERMINISTIC, 

But then when you add pod 'sqlite3/fts5', '= 3.15.0'  # SQLite 3.15.0 with FTS5 enabled to the Podfile a bunch more issues arise (of the exact same nature)

**Comment by Pulichev** [comment]
I have found a temporary solution.
Check https://github.com/stephencelis/SQLite.swift/pull/970

My podfile now:

```
pod 'SQLite.swift/standalone', :git => 'https://github.com/stephencelis/SQLite.swift', :branch => 'master'
pod 'sqlite3', '3.29.0'
```

**Comment by ryanholden8** [comment]
@stephencelis - Hope this message finds you well! You're probably scrambling with supporting the new iOS 14 release and cramped for time. I know I am haha. Anyway, wanted to call your attention to this post where it looks like the fix for supporting Xcode 12 is already in master. Would it be possible to cut a release? Thanks for considering! Maybe #1006 would also fix the root issue? 

@Pulichev - Appreciate letting us know of a workaround, this worked for me, thank you!

**Comment by NathanFallet** [comment]
Closing as it was fixed
