### ISSUE TITLE
Future of this Project

### ISSUE THREAD

**Issue by palle-k** [stephencelis/SQLite.swift#1023]
It seems that there have not been updates to this project in quite some time with the latest commit being 10 months ago and the latest CocoaPods release being in June of 2019. 
Pull requests are not being merged and issues are not being addressed to the point where it is no longer building with the latest public Xcode release without some workarounds.

@stephencelis do you have any intention of updating this project by addressing issues or merging PRs? If not, would you be willing to add additional maintainers to this project so it can be kept up-to-date?

**Comment by juanjoseluisgarcia** [comment]
Waiting for the reply of the author I can confirm that if you use this library with Swift Package Manager it builds in Xcode 12. I have the feeling that Cocoapods since never officially supported by Apple we all should migrate to Swift Package Manager. Anyways if the library is not going to be updated is a risk to keep using it.

**Comment by palle-k** [comment]
SwiftPM is of course the officially supported solution but I are using the SQLCipher subspec, which I cannot install through SwiftPM. Also, my project uses CocoaPods for everything else and CocoaPods is used to generate acknowledgements for all 3rd party libraries, so SwiftPM sadly is not a viable option for me.

**Comment by NathanFallet** [comment]
Migrating to SPM is recommended yes. I joined the maintainers team today, we're going to merge pull requests and close issues as soon as possible.
