### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by pgawlowski** [stephencelis/SQLite.swift#1031]
Last update: year ago
25+ issues from this year
Bunch of issues with new xcode.
Bunch of pull requests, all failing on travis.
Lack of communication.

My only question is: is this project alive? Cause I do not want to relay on something that is already dead and is causing a lot of trouble to handle.

**Comment by newtimber** [comment]
I wouldn't start a new project with it; but if you're already using it and the issues don't effect you, then continue using it as it's a lot of work to change to something else.

**Comment by juanjoseluisgarcia** [comment]
I was using it and got rejected on the app store because the app was unstable with 'database locked' error messages. I switched to GRDB.Swift

**Comment by Quailcreek** [comment]
Hi  juanjoseluisgarcia,
I'm looking at converting several of my apps from SQLite.swift to GRDB. Would you be willing to give me a hand getting stared?

**Comment by newtimber** [comment]
I'm just in the progress of converting and finding it very time consuming as for backwards compatibility, you have to keep the database structures the same and all the indentations are different as you have to indent the code more with GRDB. Added to which you have to convert entire projects at once as you cannot have GRDB and SQLite running at the same time. In retrospect, it would have been a better use of my time to copy the SQLite code and support that myself rather than spending hours converting existing projects to GRDB.

**Comment by juanjoseluisgarcia** [comment]
@Quailcreek @newtimber My suggestion for migrating from SQLite.Swift to GRDB is to use the SQL 'flavour' of the library. That is the one that allows us not to rewrite the entire database and it is the quickest path when migrating. I have found.

**Comment by Quailcreek** [comment]
Thank you, juanjoseluisgarcia. After beating my head against the monitor I have come to the same conclusion.

**Comment by NathanFallet** [comment]
Hello, I joined the SQLite.swift maintainers team, and we're going to merge pull requests and fix issues in the coming days. (Already a few were merged at time of writing, and we are replacing the outdated travis CI with GitHub Actions)

**Comment by Quailcreek** [comment]
Sorry but I couldn’t wait. I have already switched to GRDB.

**Comment by jberkel** [comment]
this project has been dead a few times. so far it's always come back.
