### ISSUE TITLE
Best way to implement model classes representing records of a given table?

### ISSUE THREAD

**Issue by kylejm** [stephencelis/SQLite.swift#114]
@stephencelis, hope it's okay with you to ask questions here as well as open issues :smile: ? I noticed you had a "question" label. Plus I wanted your opinion rather than asking the whole community on StackOverflow.

What would recommend as the best way of of achieving the title of this ticket?

Thanks!

**Comment by stephencelis** [comment]
That label is mostly to keep track of the number of questions that are asked here :flushed:

I really do prefer Stack Overflow because:

1. It gives the problem and solution greater visibility. Issues search is not a place people turn to for questions, generally, while Google is. Stack Overflow has great Google visibility. GitHub Issues: not so much.

2. It gives other people a more nuanced ability to weigh in: rather than the single-threaded comment approach here, you get answers with more weight, and comments with less.

I subscribe to the [`sqlite.swift`](http://stackoverflow.com/questions/tagged/sqlite.swift) tag and will answer there as often as I can. Any chance you can move your question there given the above?

**Comment by kylejm** [comment]
This are great points. Absolutely, I'll ask it on there now :sweat_smile:

**Comment by kylejm** [comment]
[Here](http://stackoverflow.com/questions/29773099/sqlite-swift-best-way-to-implement-model-classes-representing-records-of-a-give) it is :+1:

**Comment by stephencelis** [comment]
Thanks! I'm traveling but will try to sit down and write something helpful soon.

**Comment by kylejm** [comment]
Awesome, thanks man!


—






Twitter - @kylejm_

http://kylejm.io
