### ISSUE TITLE
Podspec does not pass validation

### ISSUE THREAD

**Issue by uberbruns** [stephencelis/SQLite.swift#140]
To use SQLite as a dependency of another pod it needs to be in a public or private repo. To do so cocoapods seems to require a 100% valid podspec.

I tried to figure it out by myself, but I did not come far :/

**Comment by stephencelis** [comment]
@uberbruns Oh, do you have a pod that depends on SQLite.swift? I really just need to cut a first version.

**Comment by uberbruns** [comment]
it is still a private project far from to be published – but I was splitting the data layer into a framework [1] to share it between extension, when I ran into this problem.

[1] and since I was starting to pull some other 3rd party libraries into the project I wanted to start using cocoapods, too

**Comment by stephencelis** [comment]
@uberbruns I'd like to cut a version soon for Swift 1.2 since most ongoing work will target Swift 2, but in the meantime I'd suggest creating a private Podspecs repo if you need this to work ASAP: https://guides.cocoapods.org/making/private-cocoapods.html. I'll close this ticket when there's a tagged release, though.

**Comment by mikemee** [comment]
#257 appears to cover this, so I'm closing this out as part of a general pass to get the issue count down to a manageable level. Please re-open with a comment if you feel this is not appropriate. Thanks!
