### ISSUE TITLE
Cannot submit to App Store due to Invalid Bundle structure

### ISSUE THREAD

**Issue by paoloreds** [stephencelis/SQLite.swift#152]
Hello,
I am getting the following error when submitting to App Store:
Invalid Bundle Structure - The binary file 'MyTestApp.app/SQLite.framework/SQLite' is not permitted. Your app may contain only one executable file.
If I remove the copy of SQLite.Framework into the app bundle, I am able to send the bundle to the App Store with no error, but when I download the app from via TestFlight, the app does not start as SQLite.Framework is missing.
Is there any way to link the SQLite.Framework inside MyTestApp binary, so I don't run in this issue?

Thanks,
Paolo.

**Comment by stephencelis** [comment]
This usually means you're copying the framework (SQLite.framework) as a bundle resource instead of linking it as a library. See:

- http://stackoverflow.com/questions/20251252/invalid-bundle-structure-the-app-may-contain-only-one-executable-file
- http://stackoverflow.com/questions/16424431/invalid-bundle-structure-ios
