### ISSUE TITLE
Can't use with Xcode 7 GM

### ISSUE THREAD

**Issue by zhouzizi** [stephencelis/SQLite.swift#199]
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git', :branch => 'swift-2'
but it also have many error

**Comment by stephencelis** [comment]
Would you please try again? I just updated the module map that CocoaPods depends on.

**Comment by zhouzizi** [comment]
I have add import SQLite  at the file ,but also can't use the SQLite syntax,like -> Use of undeclared type 'Query'

**Comment by fredwaltman** [comment]
I am getting similar errors: both 'Database' and 'Query' give the undeclared type error.

I did the manual install. I noticed that when I dragged the xcodeproj item into my project it has a very different structure then Swift 1.2  I don't seed Database.swift anywhere and Query.swift doesn't have a class or struct named Query.

**Comment by stephencelis** [comment]
@fredwaltman I need to write a proper upgrade guide but if you see the updated documentation/README it should provide the hints you may need. For what you're having trouble with, here are a few couple:

  - The **Database** class has been renamed to **Connection** to better communicate its purpose and to prepare for better support for multiple database access (via **ATTACH** and **DETACH**).

    Before:
    ``` swift
    let db = Database()
    ```

    After:
    ``` swift
    let db = Connection() // or SQLite.Connection()
    ```

  - Protocol extensions have enabled the **Query** structure to be refactored into three separate structures: **Table**, **View**, and **VirtualTable**. Queries are also no longer coupled to database connections and must be passed to a connection in order to be performed.

    Before:
    ``` swift
    let users = db["users"]
    db.create(table: users) { t in t.column(email) }
    users.insert(email <- "alice@mac.com")
    ```

    After:
    ``` swift
    let users = Table("users")
    try db.run(users.create { t in t.column(email) })
    let userId = try db.run(users.insert(email <- "alice@mac.com"))
    ```

**Comment by zhouzizi** [comment]
thx

**Comment by stephencelis** [comment]
Closing this out. Please let me know if your problem was unresolved!

**Comment by danycord** [comment]
Hi Stephen! I'm trying to use SQLite but when I import it, the error that appear is: "cannot load underlying module for "SQLite'. I already created the PodFile (because I saw that is necessary), but the error is the same. I configured the target dependencies, libraries and I include the reference for your SQLite.xcodeproj. Could you help me?

Tks!
