### ISSUE TITLE
Converting a row type to an AnyObject type

### ISSUE THREAD

**Issue by SuperGuillaume** [stephencelis/SQLite.swift#271]
Hi everybody,

I'd like to convert each "user" variable to an AnyObject type instead of having a Row type.
Is this possible ?

```
for user in try! db.prepare() {
    // Convert here user variable
}
```

**Comment by stephencelis** [comment]
Hey, thanks for your interest in SQLite.swift. In order to reduce noise here, the GitHub issues board is for bug reports and feature requests. (See https://github.com/stephencelis/SQLite.swift/blob/master/CONTRIBUTING.md for details.)

You should be able to extract values from `Row` and put them into another object. If you have additional questions, please ask on Stack Overflow!
