### ISSUE TITLE
Create a Bool based column and use it

### ISSUE THREAD

**Issue by sumitjain7** [stephencelis/SQLite.swift#276]
I created a column like 
  let isRead = Expression<Bool>("isRead");
and i want to add it to table 
  let chat_master = db["chat_master"];

How to do this? I guess sqllite do not support bool.

**Comment by stephencelis** [comment]
Hey, thanks for your interest in SQLite.swift. In order to reduce noise here, the GitHub issues board is for bug reports and feature requests. (See https://github.com/stephencelis/SQLite.swift/blob/master/CONTRIBUTING.md for details.)

`Expression<Bool>` should work just fine, as SQLite.swift converts the underlying value.

If you have additional questions, please take them to Stack Overflow, thanks!
