### ISSUE TITLE
Implement LLVM Modules

### ISSUE THREAD

**Issue by iNoles** [stephencelis/SQLite.swift#296]
When I tried to build an iOS application with SQLite Framework on the latest swift 2.2 snapshot, I get build failed on the sqlite3 being non-modular. 

Example of modules file looks like for sqlite3

```module <project name> [system] {
    header "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sqlite3.h"
    export *
}```

any developers have to create modules in each SDK.

**Comment by mikemee** [comment]
@iNoles , can you please give the `publicpod` branch a try, per PR https://github.com/stephencelis/SQLite.swift/pull/314.

Along with some other build simplifications, it does (almost) exactly as you've suggested ([see modulemap file](
https://github.com/stephencelis/SQLite.swift/blob/publicpod/SQLite3/module.modulemap)) and I'd love to hear if it works for you or not... as I'm not running the Swift 2.2 snapshot.

The only difference is that it references `"/usr/include/sqlite3.h"` instead of the various platform includes to keep things simple between the various build targets. Fortunately, AFAIK, `sqlite3.h` is pretty platform agnostic. If you know of a better way...  I couldn't find a way to reference different paths for different build targets. I can't wait for the Swift Package Manager to be released. It will clean up so many things!

**Comment by iNoles** [comment]
my concern about "/usr/include/sqlite3.h" would use system path, but not SDK ones.

**Comment by mikemee** [comment]
Yes, that's my concern too. I just don't have a solution...  Do you know of one?

At least a step forward...

**Comment by stephencelis** [comment]
@iNoles Please let us know if you run into issues there. Assuming the header is always available, the interface should generally be the same between the current SDK header. I'd love to have a general solution here, but it may have to wait for Swift Package Manager support and the forthcoming plans to support dynamic LLVM modules.

**Comment by iNoles** [comment]
@stephencelis I had Swift 2.2 snapshot of December 31.

It did show this error 
```quote
/usr/include/sqlite3.h:35:10: note: while building module 'Darwin' imported from /usr/include/sqlite3.h:35:
#include <stdarg.h>     /* Needed for the definition of va_list */
         ^
<module-includes>:32:9: note: in file included from <module-includes>:32:
#import "util.h"
        ^
/usr/include/util.h:107:10: error: 'utmp.h' file not found with <angled> include; use "quotes" instead
#include <utmp.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/usr/include/sqlite3.h"
        ^
/usr/include/sqlite3.h:35:10: error: could not build module 'Darwin'
#include <stdarg.h>     /* Needed for the definition of va_list */
         ^
/Users/jonathansteele/Desktop/mobile/iOS/SQLite.swift/SQLite/Core/Blob.swift:25:8: error: could not build Objective-C module 'SQLite3'
import SQLite3
```

**Comment by stephencelis** [comment]
I suppose we might need separate modules for CSQLite3_Linux and CSQLite3_Mac to support this in the meantime.

**Comment by iNoles** [comment]
I think it is a best to create a modules map on each SDK for this.

**Comment by stephencelis** [comment]
Yup. This won't unfortunately work for `Xcode-beta.app` and installations other than `/Applications/Xcode.app`, but that'll have to do till LLVM modules are more flexible.

**Comment by mikemee** [comment]
@iNoles - so can we close this now, on the basis of your comments re 0.9.2 in PR #327 ?

**Comment by iNoles** [comment]
I guess so.
