### ISSUE TITLE
32 bit platform overflow and crash with Int64 value

### ISSUE THREAD

**Issue by samw723** [stephencelis/SQLite.swift#36]
I found if I save Int64 integer value in sqlite INTEGER, it will crash while retrieve the value on iPhone5 or other 32bit iPhone, will you support BIG_INT or what opinion you have on this issue?

Although you use sqlite3_column_int64 to get value, but Int depends on platform, even if the value is Int64 on iPhone5, Int still 32bit and will overflow

    case SQLITE_INTEGER:
                let int = Int(sqlite3_column_int64(handle, Int32(idx)))
                var bool = false
                if let type = String.fromCString(sqlite3_column_decltype(handle, Int32(idx))) {
                    bool = type.hasPrefix("BOOL")
                }
                row.append(bool ? int != 0 : int)

**Comment by stephencelis** [comment]
SQLite3 treats/assumes its integers as/are 64-bit (even on 32-bit platforms), which is why there's no equivalent `sqlite3_column_int32` function.

What's the use case in which you're encountering this issue? Are you opening an existing database that has values that overflow? Are your auto-incrementing ids overflowing?

Generally, I've found that integer overflow issues are solved by:

1. Using a TEXT column instead.
2. Using a UUID instead of an auto-incrementing id.

In any case, I'm not sure this crash is avoidable otherwise, though I'm open to ideas and/or a pull request.

**Comment by stephencelis** [comment]
@samw723 I'm going to close this issue for now. I'm happy to reopen it if you would answer my earlier questions and if you still believe this is an issue on SQLite.swift's side.
