### ISSUE TITLE
module.modulemap Xcode 7.3 (7D175)

### ISSUE THREAD

**Issue by jamielesouef** [stephencelis/SQLite.swift#378]
Hi, 

I'm getting an the following errors when after upgrading to Xcode 7.3

`Redefinition of module 'Compression'`
`Redefinition of module 'Darwin'`
`Redefinition of module 'os'`
`Redefinition of module 'libkern'`

`Could not build Objective-C module 'SQLLite`

tried cleaning project, re installing pods but no luck.

**Comment by shnhrrsn** [comment]
Similar issue being tracked in #349 -- I just added some info there that may be helpful.

**Comment by vtongcoder** [comment]
I have the same issue. This one only happens when I select a Simulator device to run the app.
On my real iPhone, everything is ok

**Comment by Ryannnnnnn** [comment]
Ran into the same issue +1

**Comment by codysk** [comment]
Same issue +1
It work for real device but Simulator is down

**Comment by AliThink** [comment]
Same issue +1

**Comment by dongkaipo** [comment]
+1, but i find the update log with `.travis.yml` file.
![Uploading image.png…]()

**Comment by vinbhai4u** [comment]
+1 same issue

**Comment by fuxx** [comment]
I've added a pull request from a solution i made for my framework. In the module map i added cpu checks and based on that i include the sqlite header for arm or x86.

**Comment by AarioAi** [comment]
+1 issue occurs on Xcode 7.3 stable version (swift 2.2)

**Comment by stephencelis** [comment]
If you're using iOS, @fuxx's branch will unblock you, though it still doesn't solve build issues with OS X and tvOS. #349 has an alternative solution. I know workarounds suck, and I'd love to merge an update that fixes CocoaPods for everyone when it's available, but these solutions should allow everyone to get back to building their apps.

I will note that this issue only affects CocoaPods-based installations. CocoaPods is a great tool, but the way it works currently requires a custom module map approach that is more difficult to maintain and unfortunately rather brittle. The other installation methods (submodule, Carthage) will be more stable because they do not depend on this and will also unblock anyone encountering this error.

**Comment by stephencelis** [comment]
Would those having issues try this solution? https://github.com/stephencelis/SQLite.swift/issues/380

**Comment by jamielesouef** [comment]
Following #380 I was able to install using the CocoaPods app (Version 1.0.0.beta.5 (2016.03.14))

**Comment by Tom29** [comment]
Any solution to solve this trouble?

**Comment by jamielesouef** [comment]
@Tom29 #380 has quite a bit of information on fixes that have worked for some.

**Comment by stephencelis** [comment]
Should be fixed via merge of #380.
