### ISSUE TITLE
Build fail with Xcode 8.0 beta in Swift 2.3

### ISSUE THREAD

**Issue by joshuaavalon** [stephencelis/SQLite.swift#465]
I have noticed that this library does not support Swift 3 yet, so I tried to use it in Swift 2.3. I followed the  installation instructions (Manual). However, before I use any code related to the library, I failed the build after adding it to the framework. Here is my [full log](https://gist.github.com/joshuaavalon/e31f9a09ec046b109318a8ec9a03f383).

There errors are "Expected function body after function declarator", "Redefinition of 'fsobj_id'" and "Typedef redefinition with different types".

**Comment by p2** [comment]
Same problem here.

**Comment by jberkel** [comment]
probably time to set up a travis build w/ xcode8

**Comment by iNoles** [comment]
The iOS Framework in Xcode 8 isn't binary compatible with Xcode 7.

**Comment by jberkel** [comment]
Binary compatibility is not a problem since everything gets rebuild from source anyway. The issue is that the paths to the SDKs are hard coded in the module maps and need to be updated.

See #475

**Comment by prashanthsun9** [comment]
is there any updates on this issue?

**Comment by jberkel** [comment]
Some tests fail on the PR so can't merge back into master. As a workaround you can just rename the paths in [module.modulemap](https://github.com/stephencelis/SQLite.swift/blob/master/CocoaPods/iphonesimulator/module.modulemap) to Xcode-beta.app locally.

**Comment by mjarvis** [comment]
For those looking for an automated method of adjusting the module map for alternate Xcode install locations: `sed -i -e "s|/Applications/Xcode.app/Contents/Developer|$(xcode-select -p)|g" Pods/SQLite.swift/CocoaPods/iphonesimulator/module.modulemap`

**Comment by jberkel** [comment]
The [xcode8](https://github.com/stephencelis/SQLite.swift/tree/xcode8) branch should now be useable.

**Comment by mojidabckuu** [comment]
I've pulled xcode8 branch. It was giving me few errors on module maps.
So I checked and 
```
cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/ && ls
```
gives me `iPhoneSimulator.sdk iPhoneSimulator9.3.sdk`
So in my case the issue was that my Xcode was installed by drag and drop from *.dmg file that I downloaded from apple developer center. 
I updated my Xcode and now everything compiles 💯

**Comment by Govindakarthikeyan** [comment]
Thanks mojidabckuu. I also faced the following errors, 
"Expected function body after function declarator", "Redefinition of 'fsobj_id'" and "Typedef redefinition with different types" after integrated an iOS SDK through cocoapods. Finally I followed your solution that updating the Xcode through Appstore instead of drag & drop DMG file. After that, those errors got fixed.
