### ISSUE TITLE
select ... NOT IN

### ISSUE THREAD

**Issue by kolisko** [stephencelis/SQLite.swift#484]
Hi, I have an array of ids and want to select ids from db that are not in array. Try to find NOT IN filtering function and found only "contains" filtering function which is opposit of what I need. Does exist negation of "contains" filter?
## Example
- in db are users with ids 1,2,3,4,5,6
- in array are values 1,2,3,4,5

I want to get all ids from db except values in array, it means get id 6

want call something like this
users.filter([1, 2, 3, 4, 5].**not**Contains(id))
// SELECT \* FROM "users" WHERE ("id" **NOT** IN (1, 2, 3, 4, 5))

Thank you for any idea,
Michal

**Comment by MrMage** [comment]
Could you just use `!([1, 2, 3, 4, 5].contains(id))`? I would expect the SQLite query planner to be smart enough to optimize that query to the desired one.

**Comment by lukescott** [comment]
That's what I do, but when I try to deploy my application I get:

```
Expression type 'Bool' is ambiguous without more context
```

For some reason it compiled and runs fine in simulator without any changes...

**Comment by whoisronak** [comment]
Try to put the !([1, 2, 3, 4, 5].contains(id)) inside of a filter statement i.e. 

table.filter(!(array.contains(idExpression)))

I know this is super late but for anyone else who stumbles upon this, the above works for me.

**Comment by ronakvora** [comment]
Update: the above is super slow (7 seconds to execute using SQLite.swift syntax), but takes .15 seconds using arbitrary sql. So if you run into this issue, I would get the list of ids that are NOT IN whatever set you have using arbitrary SQL and then use SQLite.swift syntax to query the table for using contains rather than !contains. Example: 

let statementString = "SELECT id FROM products WHERE id not in \(alreadyExistingIdsString) order by RANDOM() limit 30"

var newIdsToGet = [Int]()
for newRow in try! db.prepare(statementString) {
  newIdsToGet.append(Int(newRow[0] as! Int64))
}
let productsQuery = products.filter(newIdsToGet.contains(idExpression)).order(Expression<Int>.random()).limit(30)

**Comment by MrMage** [comment]
Wow! Any idea why one is so much slower than the other?

(Tip: if you wrap code in triple backticks, it will automatically be rendered as code.)

**Comment by ronakvora** [comment]
No idea! :) If I had to guess, I'd guess that the !contains ends up being a linear scan of the DB that doesn't cut off after LIMIT rows have been retrieved whereas the contains gets transformed into a SELECT from table WHERE id = 1 or id = 2 ... or id = n; and if your DB is indexed on the id field that should be super fast.

**Comment by ronakvora** [comment]
And thanks! I'll update that.
