### ISSUE TITLE
Error sqlite3.h header not found in branch 'swift3-mariotaku'

### ISSUE THREAD

**Issue by dianambb** [stephencelis/SQLite.swift#506]
I am using the 'swift3-mariotaku' branch and bring in the pod using this:

` pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift.git', :branch => 'swift3-mariotaku'`

I see the error:
`SQLite-Bridging.m:26:9: 'sqlite3.h' file not found`

**Comment by zigool** [comment]
me too! 😞

**Comment by sam-w** [comment]
I bet you have your Xcode 8.x named something sensible like `/Applications/Xcode 8.app/`. If you rename it, or create a symlink, so that it can be found at `/Applications/Xcode.app/` you should find that it builds successfully. 

This error is due to the path being hardcoded in `Metadata/CocoaPods/iphoneos/module.modulemap` (a file which will be used even if, like me, you're using SQLite with Carthage).

**Comment by sam-w** [comment]
@dianambb  @zigool FYI

**Comment by jberkel** [comment]
@sam-w the master branch should not use the modulemap w/ carthage now.

**Comment by jberkel** [comment]
closing this, should be fixed in 0.11.0
