### ISSUE TITLE
Reinitializing Database Schema on Application Update

### ISSUE THREAD

**Issue by Laptopmini** [stephencelis/SQLite.swift#526]
I am currently developing an app which gets released through TestFlight (and soon to the AppStore hopefully). 

I have thought of a scenario which I would like to prevent and was wondering if you guys had advice, since some of you might have met it. 

**I would like to have the database reinitialize itself every time the application is updated.** 

At the moment, each time my app is opened I run a series of commands to create the tables if they do not exist:

```
try db.run(messagesTable.create(ifNotExists: ifNotExists) { t in
    ...
})
```

However, if I change the schema of the db between updates, and a User updates to the latest version, SQlite will not reinitialize the table since it already exists (even though their schema is different). 

I am scared that a user might update his application and fail to run it until he manually removes the app and does a clean install, which would force SQlite to initialize all the tables correctly.

Am I wrong to assume this scenario will happen? If no, is there a way to trigger a drop of the tables on an app update?

The only way I can think of at the moment, would be to save the app version number to disk, and if it changes then reset the database, but I figure I'd ask here to see if there was a more "SQL" way of doing it. 

Thanks!

**Comment by jberkel** [comment]
Storing a schema number in the db itself is the usual way to go. You could use [pragma_user_version](https://sqlite.org/pragma.html#pragma_user_version) to store this information, you don't even need to create a separate table.

**Comment by Laptopmini** [comment]
Is there a way to get all the current tables in the database?

It seems you can only drop a table using a `Table` variable on which you call `drop()`, and if a user updates from a very outdated version of my app, he might have a table in his database which might not be declared in the app's code anymore.

Until now, if the schema version would change, I would cycle my `Table` variables, calling `.drop()` on each one of them. How can I call `.drop()` on any table which I do not have defined?

My idea was to get the list of tables from the database, then filter out the ones I have definitions for, and drop any remaining name. I can obviously figure out a way to do this in raw SQL, but I was hoping there might be some methods to help me with this?

As for the motivation behind this: I want to guarantee that schema updates clear out old tables as to guarantee no conflicts in the future or have the database schema grow out of control because it wasn't throwing out its trash. :)

**Comment by groue** [comment]
SQLite.swift shares table and column (expression) objects between regular queries, and the schema setup. As you notice quite well, this is a problem as soon as the application code is updated and does not reflect any longer the actual schema of the database file.

Other database libraries like Core Data, Ruby's ActiveRecord, or GRDB.swift, don't do that: they make sure that the code that defines and migrates the database schema is *strictly* separated from the regular operations. In order, precisely, to avoid this very problem you are facing.

Your solution is thus to bring back this isolation **yourself**, since SQLite.swift does not do it for you: **Don't share** tables and expressions between migrations and regular operations. **Isolate** your migrations. Let them use obsolete tables and columns, since this is precisely their job.

Your application code will be much cleaner, since the future database schema updates will not need already written migrations to be changed. Your code will also be more verbose, because you'll have to declare table and column expressions twice. That's the consequence of an unfortunate design decision - but your application maintenance is more important than a little code duplication.

**Comment by Laptopmini** [comment]
After trying to execute statements directly to get the list of tables in the database (`.tables`) without any success, I am going to wait and see what the library has to offer in migrations, once the section for it has been filled out: 

https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#migrations-and-schema-versioning

If anyone has tips on how to use, I'll gladly take 'em.

**Comment by stephencelis** [comment]
> After trying to execute statements directly to get the list of tables in the database (.tables) without any success, I am going to wait and see what the library has to offer in migrations, once the section for it has been filled out:
>
> https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#migrations-and-schema-versioning

@Laptopmini I'm not quite sure what happened to that section, but this issue outlines the schema versioning pretty plainly: https://github.com/stephencelis/SQLite.swift/issues/456#issuecomment-227412133

Meanwhile, @groue has some things right: migration code should be isolated. Core Data and Active Record isolate by tooling and convention, while SQLite.swift is a lightweight library that allows you to work with whatever convention you want. There is no requirement that SQLite expressions must be shared among schema setup and regular queries (you are free to organize this code however you'd like to). You could avoid the expression layer altogether! It's your choice. GRDB has some strong opinions, respectable boundaries, and interesting ideas (some of which I'm sure SQLite.swift could benefit from, as GRDB has benefited from SQLite.swift)—maybe a Rails/Merb-like merger is in order? 🤔

In the end, nothing is stopping anyone from writing their own migration manager using SQLite.swift. In fact, someone has, here: https://github.com/garriguv/SQLiteMigrationManager.swift

**Comment by jberkel** [comment]
I tend to agree on the GRDB/SQLite.swift differences. A while ago, somebody asked  about "best practices" for using  SQLite.swift. This is tough to answer, since the library can be used in many different ways, that's the whole point of it. 

Beginner to intermediate developers are probably better served with GRDB.swift since a lot of decisions have already been made there.

**Comment by groue** [comment]
@jberkel I believe advanced developers won't feel limited with GRDB, even if it indeed attempts at preventing beginners from falling into common traps. But I may be mistaken: I'd be curious to hear from other demanding SQLite users about GRDB pain points.

**Comment by jberkel** [comment]
@stephencelis I restored the migration docs on the point release branch (#531)
@groue very likely, especially since it offers a separation of high vs low-level api. I haven't tried it out myself though, so can't comment on pain points.

**Comment by jberkel** [comment]
Closing this -  in the meantime https://github.com/garriguv/SQLiteMigrationManager.swift has been updated and should be usable (docs updated to reflect this).
