### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by nuclearace** [stephencelis/SQLite.swift#60]
Should look into updating for Swift 1.2

http://adcdownload.apple.com//Developer_Tools/Xcode_6.3_beta/Xcode_6.3_beta_Release_Notes.pdf

**Comment by fantattitude** [comment]
There's a migrator in this Xcode release to go from 1.1 to 1.2 code.
Maybe you could give it a try…

**Comment by preble** [comment]
I took a pass at it and found that there are many uses of `@autoclosure` that are no longer valid, since it is now a qualifier on a parameter and not a type. However, since `@autoclosure` implies `@noescape`, and `dispatch_sync` isn't `@noescape` ([radar](http://openradar.appspot.com/radar?id=5525816138006528)), I took the approach of changing the `perform()` locking mechanism to use an `NSRecursiveLock` instead of a queue.

Unfortunately I got stuck when the swift compiler was segfaulting on `Expression.swift`. :frowning: I think it must be something that's changed by this process because it doesn't crash prior to the conversion.

**Comment by stephencelis** [comment]
@preble Thanks for looking into things :smile:. The upgrade's actually a bit more complex than what I'd hoped, but I've started a branch.

Going to close this issue in favor of tracking the PR: https://github.com/stephencelis/SQLite.swift/pull/62

**Comment by preble** [comment]
Thanks, @stephencelis, for jumping on this!
