### ISSUE TITLE
xcode 8.3 error

### ISSUE THREAD

**Issue by WDDong** [stephencelis/SQLite.swift#617]
Project builds fine in Xcode 8.2.1, but in  Xcode8.3 beta4 the pod SQLite.swift produces >18 issues like:
`Swift Compiler Error 
  Build a shadowed submodule 'Darwin.POSIX.basic' 
  module.modulemap`
`build a shadowed submodule 'Darwin.POSIX.sys.types._int8_t'`

Is there a simple resolution/workaround?

**Comment by jberkel** [comment]
@WDDong make sure you follow the instructions exactly, especially step 1)

https://github.com/stephencelis/SQLite.swift#cocoapods

**Comment by michalseverin27** [comment]
@jberkel we are sure about install. This pod isn't usable with Xcode 8.3 for this time..

**Comment by ibadcool** [comment]
@ryanholden8 I tried ur setup, but with Xcode8.3 release,  it build failed.  
error:  'sqlite3.h' file not found

**Comment by jberkel** [comment]
0.11.3 has been tested with Xcode 8.3, closing.

**Comment by StevenMasini** [comment]
I just got the same problem in my project too with the version 0.11.3, but **I solved this problem.**
Just for the record I post the solution that worked for me.

This error was trigger because I had two version of XCode on my computer, 8.3.3 and 9.1.

XCode 9.1 was named "XCode" and XCode 8.3.3 was named differently. The project that use the SQLite framework was running with XCode 8.3.3.

So the solution was to have XCode 8.3.3 renamed in "XCode" instead of the XCode 9.1.

**Comment by nickolayl** [comment]
> This error was triggered because I had two versions of XCode on my computer, 8.3.3 and 9.1.
> 
> XCode 9.1 was named "XCode" and XCode 8.3.3 was named differently. The project that use the SQLite framework was running with XCode 8.3.3.

Confirm. Helped!
