### ISSUE TITLE
Compile Error: Redefinition of module 'CSQLite'

### ISSUE THREAD

**Issue by jeffreylyg** [stephencelis/SQLite.swift#620]
$ProjectRoot/Pods/SQLite.swift/CocoaPods/appletvsimulator/module.modulemap:1:8: Redefinition of module 'CSQLite'

**Comment by 4floor** [comment]
help!help! I have the same error!

**Comment by abushnaq-work** [comment]
Any luck getting past your issues?

**Comment by SebastianOsinski** [comment]
Has anyone of you managed to fix this error?

**Comment by Mikebanana** [comment]
help!help! I have the same error!

**Comment by jberkel** [comment]
FIY, this error should be gone with the latest version (0.11.4).

**Comment by umarfarooq21** [comment]
I updated the import CSQLite statement with SQLite3 error resolved....

**Comment by guyzmo** [comment]
Hi, I'm having the same error, and it looks like something is broken in the `modulemap` resolution. When in `SQLite.swift/CocoaPods/` I remove every directory but the target I'm building for (`iphonesimulator` or `iphone` depending on whether I'm building a debug or a release), it compiles fine.

I guess this solves only the consequence of the problem, not the root cause… If anybody could hint me how to solve this, it'd be great ☺

P.S.: I'm running 0.11.2, I cannot upgrade to 0.11.4 yet as it's being pulled with a fixed version by a dependency I need.
