### ISSUE TITLE
recent update 0.11.3 doesn't support minimum deployment iOS 8 ?

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [stephencelis/SQLite.swift#625]
while trying to update the pod from 0.11.2 to 0.11.3 the following message appears on the command line:

"Specs satisfying the 'SQLite.swift (~> 0.11.3)' dependency were found, but they require a higher minimum deployment target"

I am using a minimum deployment target iOS 8 , swift 3, Xcode 8.3

**Comment by nestserau** [comment]
Had this too. I don't see any reason for the minimum version switch other than emotional. The code in the library doesn't require iOS 9 features. I had to fork the 0.11.2 version of the library and patch it with the latest commits but leaving the minimum version at 8. I already regret that I've started using this lib. But now it's just too late to change anything.

**Comment by jberkel** [comment]
Sorry, maybe this was a little bit too fast. I'll restore 8.0 compatibility with the next release, in any case there aren't any critical fixes in 0.11.3, so you can just lock to 0.11.2 for now.

**Comment by gioneill** [comment]
With Xcode 9 and Swift 4 coming up, I'm going to be forced to fork like @nestserau to manually decrease the deployment target so that I can build with the current dev tools.

We support numerous education and low-income users across the US that distribute iPads that are not always kept up to date, and we strive to keep that support going without causing disruptions to teachers' curriculums.

I'm thankful for this dependency, and love it in general, and I'm typically of the opinion that as long as the deployment target CAN stay where it is, there shouldn't be motivation to move it up.

**Comment by jberkel** [comment]
@gioneill i tend to agree, the only problem from a maintenance point of view is testing / making sure everything still works on older platforms. is it / will it be possible to deploy swift 4 apps on iOS 8?

we would need to install the older SDKs / simulator images with travis. maybe this could be done with [xcode-install](https://github.com/KrauseFx/xcode-install).

**Comment by jberkel** [comment]
0.11.4 reverted to 8.0.
