### ISSUE TITLE
Any document on how to use SqlCipher?

### ISSUE THREAD

**Issue by zhouhao27** [stephencelis/SQLite.swift#667]
I encrypted a sqlite database by DB Browser for Sqlite with a password. Then I'd like to know how to use it in my application. Here is my code.

```
        do {
          self.connection = try Connection(Database.storeURL().absoluteString)
          try self.connection.key("password")
        } catch {
            fatalError("Could not setup database")
        }

  static func storeURL() -> URL {
    guard let documentsURL = URL(string: NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]) else {
      fatalError("Could not get user documents directory URL")
    }

    return documentsURL.appendingPathComponent("local.db")
  }
```

I manually copy my encrypted local.db to my Simulator Document folder. But when I run the application, the app is never return from self.connection.key("password").

Any idea? Thanks.

**Comment by zhouhao27** [comment]
Nobody using SqlCipher

**Comment by mingsai** [comment]
I did set up an empty test project and confirmed that if one can get the subspec pod to compile; the following just works.  I used this [procedure](https://discuss.zetetic.net/t/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher-and-avoid-file-is-encrypted-or-is-not-a-database-errors/868) to encrypt the db. Based on this outcome (and after battling a number of errors); one should be able to use the regular SQLite calls after calling the key function. Caveat (large queries seem to be slower), mileage may vary. 

> ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'secret'; -- create a new encrypted database
> CREATE TABLE encrypted.t1(a,b); -- recreate the schema in the new database (you can inspect all objects using SELECT * FROM sqlite_master)
> INSERT INTO encrypted.t1 SELECT * FROM t1; -- copy data from the existing tables to the new tables in the encrypted database
> DETACH DATABASE encrypted;

If you get "not a file..." or database errors, check that the copied file accessed in code is actually and truly encrypted by opening first in [db Browser for SQLite](http://sqlitebrowser.org/). Would be great to have the subspec rolled into the master so that this extension is available without jumping through hoops, then I'd just use Carthage. As it stands, I'm not sure I will keep going with pods. 

**TESTING ENCRYPTED DB**

```
func testCipherKeyAccess(){
    //get the encrypted data base
    guard let db = try? Connection(sctTests.getPath(fileName: self.filename)) else {
      XCTFail()
      return
    }
    debugPrint("Connection:",db)
    debugPrint("Writeable?: \(!db.readonly)")
    do {
      //validate the key
      try db.key("secret")
      debugPrint("Secret Key accepted")
      try db.execute("SELECT * FROM medicine")
      debugPrint("SELECT executed")
      //standard SQLite
      let medicineTable = Table("medicine")
      debugPrint("Table referenced")
      var output:[Medicine] = []
      let medicines = Array(try db.prepare(medicineTable))
      debugPrint("Statement Prepared")
      XCTAssert(output.isEmpty, "Outeput array has unexpected values")
      XCTAssert(!medicines.isEmpty)
      output = try medicines.map({ (row) -> Medicine in
        try row.decode() as Medicine
      })
      XCTAssert(!medicines.isEmpty, "Array is not mapped")
      debugPrint("Array mapped:")
      debugPrint(output.count)
      XCTAssert(!output.isEmpty)
      
    } catch  {
      
      debugPrint(error, error.localizedDescription)
      XCTFail()
    }
  }
```
