### ISSUE TITLE
Transform Row to JSON

### ISSUE THREAD

**Issue by wassimseif** [stephencelis/SQLite.swift#711]
Is there a way to transform the `Row` returned from querying the database to ` [String : Any]`. This makes initializing classes from `Row` very easy since most classes have a helper method to initialize them from a dictionary

**Comment by Matthew-Shannon** [comment]
This would be very helpful!

**Comment by shanno29** [comment]
As of right now it's impossible to unit test a function such as:
func rowToModel(row: Row) -> SomeModel 

With Row having filePrivate access modifiers there is no way to create a "dummy" or mock Row. Creating a method like row.toDictionary() would fix this entirely due to not having to pass a Row object around.

**Comment by wassimseif** [comment]
yes of course. it should be a method in `Row`. I guess the best approach would be something life this 
```
var products = [Product]()
for productRow in try! db!.prepare(productsRowsResultedFromQueryingTheDatabase) {
    let newProduct = Product.initFrom(JSON : productRow.toJSON())
    products.append(newProduct)
}
```

**Comment by wassimseif** [comment]
any updates on this ?

**Comment by jberkel** [comment]
In the release branch `Row` has now internal access so should be usable for unit testing.

**Comment by jberkel** [comment]
with the internal access you should be able to do 

```swift
@testable import SQLite
extension Row {
  var asJSON: ...
}
```
