### ISSUE TITLE
Any suggestion on scheduler deletion of record

### ISSUE THREAD

**Issue by zhouhao27** [stephencelis/SQLite.swift#721]
I need to scheduler some housekeeping jobs in my application to delete some records. I setup timer for this. And inside timer closure, I'll delete certain records. But my question is what is the best practice to do so since I could be in certain screen which is using some of the records.

**Comment by bpo217** [comment]
The short answer?  There is no right way.  

There are many ways to write an application with the description you provided.  You need to learn about multi-threaded design patterns and implement one which you feel is best suited to your problem.  One that's prewritten for you is the Notification Center in Foundation.  You can setup different parts of your application (such as a table view controller) to respond to a particular notification (like the deletion of a record) and update your UI accordingly.  

Also, deleting records from another thread using SQLite.Swift's Connection is fine because it uses a serial dispatch queue behind the scenes.  

Also, this question is completely out of scope for this library.  This is more like a stack overflow question.  

Good luck!
