### ISSUE TITLE
Xcode 9.2 Beta

### ISSUE THREAD

**Issue by Feridunt** [stephencelis/SQLite.swift#755]
Hi

I install SQLite.swift with cocoapods and use it in my project with Xcode 8.2.1
Today i download Xcode beta 9.2 and opened my project 

But it gives error 
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.2.3

I reinstall it with cocoapods without a problem.
Other pod which i used before doesn't give any error but just sqlite gives that ...

Regards

**Comment by mingsai** [comment]
This just means you need to rerun the pods again so that they are recompiled. Close the project and run pod update. The pods will be recompiled with the current version of Swift in that project. If there are further issues search for LEGACY in your build section and verify that you are working with the correct version of Swift on the updated project.

**Comment by jberkel** [comment]
please retry with the latest version and reopen if needed
