### ISSUE TITLE
/Users/yth/Xcode/test/Pods/SQLite.swift/Sources/SQLiteObjc/fts3_tokenizer.h:27:9: 'sqlite3.h' file not found

### ISSUE THREAD

**Issue by theanhoo** [stephencelis/SQLite.swift#991]
MacOS 10.15.3 (Catalina)
Xcode 11.3.1 (1C504)
Target: iOS, 13.2
Integrating using CocoaPods

I am using pod `'SQLite.swift', '~> 0.12.2'` successfully but I am not able to use it with `sqlilte3/fts5`.

If I use add `pod 'sqlite3/fts5', '= 3.15.0'` in my Podfile, build will fail with 'sqlite3.h' file not found.

Please advise.

Many thanks in advance.

**Comment by zachwick** [comment]
@theanhoo You may have some luck following the [example in the docs](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#requiring-a-specific-version-of-sqlite) which shows how to use `SQLite.swift` with the `sqlite3/fts5` pod.

Also, you should ensure that after you've installed (via `pod install`) your various dependencies, you are opening your project via its Xcode workspace file `App.xcworkspace` so that cocoapods can munge your build paths as it needs to.

If none of these solutions get your project building, can you share what your `Podfile` looks like?

**Comment by NathanFallet** [comment]
Try again using `0.13.0`, it should be fixed. If not, please open again this issue.
