### ISSUE TITLE
how to use unique?

### ISSUE THREAD

**Issue by mstfabbstbr** [stephencelis/SQLite.swift#992]
i don't want to let user, insert a duplicate value in table.. how to use unique?

**Comment by zachwick** [comment]
@mstfabbstbr The [documentation](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#column-constraints) for the `column` function shows how to use the `unique` parameter to create a constraint on the column.

If you need to create a unique constraint across multiple columns, then you'll want to look at the [documentation](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#table-constraints) for table constraints.

**Comment by mstfabbstbr** [comment]
Hey, thanks a lot for this. That helps me a lot.. thank you.

**Comment by mstfabbstbr** [comment]
hey, thanks again for your email, i’ve one more question. when you create a database, it’s create in whole app, or just in that viewcontroller? 

because i wanna use one of table i created in another controller, it’s possible?

**Comment by TenMaKo** [comment]
As stated in [documentation](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#connecting-to-a-database), when you do `let db = try Connection("\(path)/db.sqlite3")` for the 1st time, it creates a database file at path "\(path)/db.sqlite3" so it's not a matter of controller, it's about accessing this file. So yes you can access your database from any controller, you just need to do the same thing again in order to access the same file.

But maybe you should document yourself on how to implement a data access layer before jumping into code, it will help you a lot.
Take your time to really understand [this](https://github.com/stephencelis/SQLite.swift#usage) and take a look at the proposed example at the end of the section.
